[workspace]
authors = ["uv-xiao <shallwexiao@gmail.com>"]
channels = ["conda-forge"]
name = "diary"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pandas = ">=2.3.0,<3"
matplotlib = ">=3.10.3,<4"
openpyxl = ">=3.1.5,<4"
